### ISSUE TITLE
Add support for Sequel

### ISSUE THREAD

**Issue by neilmiddleton** [neilmiddleton/attr_secure#2]

**Comment by neilmiddleton** [comment]
@dmathieu - feeling lucky?  It'd be great to have adapters for AR and Sequel that we can drop use and test independently.

**Comment by dmathieu** [comment]
That's definitely a good idea.

**Comment by neilmiddleton** [comment]
I guess ideally, we want this to work on a PORO, but also with AR, Sequel and maybe Datamapper (although we don't use that).  BTW you have commit access :thumbsup:

**Comment by dmathieu** [comment]
I've seen that, thank you. I will have some time in a train tomorrow morning to hack on this.
I'll focus on refactoring it to make it easy to plug any adapter.

**Comment by neilmiddleton** [comment]
AR is now separated out into an adapter (https://github.com/neilmiddleton/attr_secure/commit/a7063aa06929f2697c14951b542ee2a3085c65fb).  Just need to figure out how to get Sequel working.

**Comment by dmathieu** [comment]
Actually, I have this almost working with ActiveRecord and pure ruby adapters in a branch on my home computer.

**Comment by neilmiddleton** [comment]
ah, interesting.  I'm working on Sequel right now, but it'd be good to see what you have.

**Comment by dmathieu** [comment]
I had intended to push it in a branch anyway. Will clean it up and push this evening.

**Comment by neilmiddleton** [comment]
Done
