### ISSUE TITLE
Less stubbing

### ISSUE THREAD

**Issue by neilmiddleton** [neilmiddleton/attr_secure#3]
Need to figure out a way to test that we're actually using Fernet accurately and correctly.  At the moment our tests are completely stubbing it out, which means we have no way of knowing if we're correctly using our underpinning library until it makes it into an app.

**Comment by dmathieu** [comment]
That would be a single integration test. We can easily do it once we have different adapters and the PORO support.
Right now, it'd mean connecting to a live database.

**Comment by dmathieu** [comment]
This is fixed with the merge of #4
